성영준/boj_14719_빗물.java
구현이라고 생각하며 풀었습니다.
`처음 문제를 보자마자 생각했던 풀이`는 따로 있었습니다.
`stack`에 `입력 받은 수`와 `index`를 함께 `저장`하고, `입력 받은 수`와 `stack의 최상단 수`를 `비교`하며 진행하는 풀이었습니다.
먼저 stack의 최상단 수 보다 `작다면`, 그대로 `add`합니다.
`같다면`, `최상단 수를 갱신`합니다.
만약 stack의 최상단 수 보다 `크다면`, `현재 수에서 최상단 수를 차이`를 구한 후, `현재 index에서 그 다음 최상단 수의 index만큼 차이`를 `곱한 값`을 구합니다.
이 과정을 현재 수보다 크거나 같은 수가 나올 때 까지 진행한 후, 과정을 진행하며 `구한 수를 모두 더하는 풀이`를 생각했습니다.
하지만 이 풀이가 효율적으로 되려면 수를 한 번에 한 번씩 입력 받는 문제여야 했기에 `다른 쉬운 풀이`를 떠올렸습니다.
일단 문제의 설명을 보고 `2차원 배열`로 구현을 한 후 한 줄씩 보며 벽을 만나고 다음 벽을 만나기까지 `사이의 값을 모두 더하는 풀이`를 떠올렸습니다.
하지만 2차원 배열로 할 필요 없이 `수의 크기 비교` 만으로도 가능하다는 것을 파악하였고 `지금의 풀이`로 해결하였습니다.
=> [BOJ] 14719. 빗물☔

여아정/boj_1062_가르침.java
백준 1062번 가르침 문제 풀었습니다.
사용한 알고리즘은 비트마스킹과 재귀입니다.
문제를 보고 비트 마스킹을 사용해야겠다고 생각했습니다. 
문제에서 확인 해야 할 부분이 몇 개 있습니다. 배울 수 있는 알파벳은 `k`개 만큼만 배울 수 있습니다. 모든 단어는 `anta****tica`의 형태로 입력이 주어지므로 초기에 `antatica`에 사용되는 알파벳은 이미 배우고 시작하는 겁니다. 즉 5개의 알파벳은 배우고 시작하므로 실질적으로 `k-5`만큼의 알파벳을 추가적으로 배울 수 있다는 점을 알아두고 시작해야 합니다. 
주어진 단어들에서 중간 `anta**tical`에서 `**`에 해당되는 알파벳들을 하나의 변수`all`에 비트 마스킹을 하여 모두 표시합니다.
재귀를 이용하여 배울 수 있는 단어 `all`중에 최대 `k-5` 만큼 씩 추가로 배운 경우에 총 몇 개의 단어를 알 수 있는지 카운트를 세서 최대 값을 출력합니다.
문제 자체는 재귀를 이용하는 단순한 형식이었지만, 비트 마스킹을 이용해야 했기에 비트 마스킹으로 조건을 다는 과정에서 오류도 잘 나고,, 단어 카운트를 세는 과정에서 처음에는 완전탐색을 이용하였어서 시간초과도 나고했습니다...
비트 마스킹 공부해야겠습니당......🥲
=> [BOJ] 1062. 가르침

성영준/boj_1062_가르침.java
보자마자 비트마스킹과 조합이라는 생각을 하였고 그렇게 풀었습니다.
무언가 `일치 여부`를 볼 때, `32개 이하`라면 `비트마스킹`을 해야겠다는 생각을 떠올리는 연습을 해서 바로 떠올리고 적용할 방법을 생각했습니다.
각 단어를 완성할 때 필요한 알파벳의 조합들이 모두 갖춰줘야 하기에 그냥 `완전 조합`을 해야겠구나 생각하고 풀었습니다.
처음에는 단순하게 필요한 알파벳인지 따로 검증하는 코드는 추가하지 않고 풀어서 116ms가 나왔었습니다.
그런데 다 풀고 보니 굳이 언어를 구성하지 않는 알파벳도 돌면서 확인할 필요가 없다는 생각을 했습니다.
그렇게 현재 풀이가 나오게 되었습니다.
하지만 생각보다 처음 풀이와 속도 차이가 얼마 나지 않았습니다.
그리고 `비트마스킹`을 적용한 코드의 경우 `디버그가 상당히 힘들다`는 것도 알게 되었습니다.
또한 과정 중에 필요한 알파벳만 모아 놓고 이 중에서만 탐색하도록 해보니, 필요한 알파벳의 수가 가르칠 수 있는 알파벳 수보다 적을 때 재귀의 가장 하단 깊이에 도달하지 못하는 오류가 생겨서 이를 해결했습니다.
=> [BOJ] 1062. 가르침🏫

soomin/BOJ_1062.java
1062를 풀었습니다.
세가지 경우로 풀었습니다.
1. K<5일 경우 무조건 0 => 접두사와 접미사에 오는 알파벳은 a,c,i,n,t로 총 5개의 알파벳임 그거보다 적으면 읽을 수가 없음
2. K == 26일 경우 무조건 N개 => 알파벳 전부를 알려줬기 때문ㅇ
3. 그 외의 경우는 조합으로 K-5개의 알파벳을 선택하여 읽을 수 있는 최대 단어 수를 구합니다.
방문처리와 어떤 알파벳들을 선택했는 지는 비트마스크를 사용했습니다.
`|` 알파벳 추가
`&` 알파벳 조회
조합을 헷갈려서 순열로 구현하여 오래걸렸습니다. 처음 조합을 배웠을 때도 재귀를 할 때 항상 틀렸던 부분을 또 틀리고 있어서 반성합니다...
=> [BOJ] 1062 가르침

soomin/BOJ_1062.java, soomin/BOJ_14719.java
구현을 생각했습니다. 단순하게 while문으로 오른쪽부터 왼쪽으로 보면서 크거나 같은 높이 가 나오면 웅덩이가 생기고 없으면 웅덩이가 없다고 생각했습니다. 근데 어떻게 구현할지 고민하다가 답을 봤습니당...
제가 본 로직은 왼쪽에서 오른쪽으로 블록을 보면서 현재 블록 기준으로 왼쪽을 돌면서 가장 큰 높이를 구하고 오른쪽으로 돌면서 가장 큰 높이를 구해서 그 두 높이 중 작은 쪽이 최종 물높이가 된다. 그래서 최종 물높이 - 현재 블록 높이를 구해 빗물을 구한다. 
처음에 틀렸는데 틀린 이유가 제일 첫번째 블록과 마지막 블록은 볼 필요가 없지만 또 왼쪽을 돌때는 첫번째 블록도 봐야하구 오른쪽으로 돌때는 젤 마지막 블록도 봐야한다. 그래야 최종 물높이를 구할 수 있응게 그래서 그거 고치니까 바로 됐당!!
예전에 푼적이 있는 문제인데 또 답을 보게 되어서 분하다...
=> [BOJ] 1062 빗물

성영준/boj_1062_가르침.java, 성영준/boj_1700_멀티탭_스케출링.java, 성영준/boj_1806_부분합.java
`단순한 투포인터 문제`라고 생각하고 풀었습니다.
이 문제도 3달 전에 풀었지만 기억이 어렴풋이 남았기도 하고, 기본적인 투포인터 문제라 쉽게 접근하고 풀었습니다.
그런데 `까다로운 case 하나`와 `문제를 제대로 읽지 않아서` 2번 틀렸습니다.
까다로운 case는 우측 포인터가 범위를 벗어났을 때, 좌측 포인터가 움직일 수 있을 경우를 생각 하지 않고 탐색을 멈추는 부분이었고,
문제를 제대로 읽지 않은 부분은 s보다 커지는 순간이 없을 때 0을 출력하라는 부분이었습니다.
어제 멀티탭 스케줄링을 풀 때도 문제를 제대로 읽지 않아서, 메모리적으로 비효율적인 코드를 작성했었는데 오늘도 같은 실수를 반복했네요
반성하겠습니다람쥐 유유
그리고 `3달전 제 풀이`도 한번 다시 보았는데
지난 문제도 그렇고 지금의 제 코드가 더 직관적이고 조건도 더 보기 쉽게 구분했네요 하핫^^
또 이 문제의 태그에 누적합도 포함되어 있었는데, 3달 전 제 풀이도 `누적합을 활용한 풀이`더군요
그런데 사실 `이 문제의 경우 누적합을 굳이 사용하지 않아도 되는 문제`이기에 지금 풀이가 더 좋아졌다고 생각합니다
누적합도 사용한 풀이가 궁금하시면 구경 한번 하🍤!
+ `깃 커밋 내역이 쌓이는 이유를 모르겠습니다`
시도해보려 노력했지만 실패했네요 유유
깃공부 해볼께요..
성송합니다..
=> [BOJ] 1806. 부분합➕

여아정/boj_1700.java, 여아정/boj_1806.java
백준 1806 부분합 문제 풀었습니다.
처음에는 알고리즘이 투포인터로 알고 풀었습니다.
투포인터로 푸는데 (2중 for문 사용함) 시간초과가 나서(시간초과 날만 했음) 이 부분을 어떻게 수정해주면 좋을지 질문게시판에 들어갔습니다. 그러다가 누적합을 이용하면 좋다는 말에 누적합을 이용하려다가 누적합 없이 그냥 투포인터만 써도 될 것같았습니다.
투포인터 구현이 기억나지 않아서 투포인터를 공부하고 다시 코드를 작성했습니다. 그랬는데 자꾸 71% 와 75%에서 자꾸 틀려서 열받았습니다......예...............
그 결국 답지를 봤는데 그 로직 순서 차이 여서 더 열받군요.........
그니까 값을 변경해줬다면 그 변경해준 값이 `s`이상이 되는지 확인하고 다음으로 포인터를 이동시켜야하는데 무조건 다음 포인터부터 이동하고 값을 확인하니까 제대로 확인이 되지 않았던 것입니다...............
저는 그냥 큰 알고리즘 못쓰는 문제가 아니라 이런 사소한 로직 순서 때문에 시간 많이 끄는 경우가 많은데... 정신좀 차리고 문제 푸는 연습 해야겠쑴다.... 
투포인트 오랜만에 풀어서 좋았숨다
하핫..
커밋 왜자꾸 쌓이는 걸가유...ㅇ유유유유
=> [BOJ] 1806. 부분합

성영준/boj_16916_부분_문자열.java, 성영준/boj_1916_최소비용_구하기.java
kmp라는 것을 인지하고 풀었습니다.
오랜만에 보는 `kmp` 문제네요
싸피에서 플레 문제로 풀다가 브론즈 문제인걸 확인하고 코웃음 쳤는데
3시간 4시간이 지났네요 하핫^^;
처음 오류도 일치하는 횟수를 출력하다가 틀렸네요
풀고 플레문제랑 비교하니 풀이가 일치하는데,
while 문을 true로 고정하고 아래에 if문으로 탈출조건 준 부분과,
continue를 사용해서 조건을 자르는 부분이 추가된 것이 다르네요
kmp `어려웡`카 유유
=> [BOJ] 16916. 부분 문자열📑

soomin/BOJ_1806.java
초ㅑ핫 
처음봤을 때는 문제를 대충 읽어서 윈도우 슬라이스인가 했는데 최소 길이를 구하려면 길이가 유동적이어야 하므로 투포인터를 생각해봤습니다.
이중 반복문을 썼습니다? 시작점이 1씩 증가하는 반복문 안에 끝점의 위치를 부분합이 S이상이 될 때까지 이동하는 반복문이 있습니다.
1. 시작점과 끝점이 첫번째 인덱스를 가리키게한다.
2. 현재 부분합이 S보다 같거나 크다면 길이를 구해서 최소 길이인지 보고 최소면 갱신한다. 그리고 반복문 종료
3. 현재 부분합이 S보다 작다면 끝점 인덱스를 +1 한다.
4. 현재 부분합이 S보다 같거나 크다면 시작점을 +1 한다.
---
* 틀린 이유 => 투포인터라고 해서 무작정 변수 두개를 만들었는데 거기서 헷갈렸다. for문으로 시작 위치를 계속 증가시키는데 이때 사용한 인덱스 변수로 길이나 입력받은 배열의 원소에 접근해야하는데 앞서 만든 start라는 안쓰이는 변수를 사용해서 틀렸었다. 금방 찾아서 다행
* 두번째 틀린 이유 => 가능하지 않으면 0이 출력되야한다는 조건을 몰랐었다. 이부분은 질문게시판 보고 깨달았지롱
그리고 여기서 성영준비된인재가 알려준 방법으로 코드를 짰다. 처음에는 최소 길이를 저장하는 변수를 출력했는데 이러면 조건문으로 0을 출력하거나 최소 길이를 출력해야하기 때문에 result 변수와 len 변수를 두고 아래와 같이 짰다. 좋은 방법 인듯
```java 
result = 0;
len = Integer.MAX_VALUE;
result = len = Math.min(len, end-start);
```
=> [BOJ] 1806 부분합 🈴

성영준/boj_1197_최소_스패닝_트리.java, 성영준/boj_1806_부분합.java, 성영준/boj_1916_최소비용_구하기.java
`프림 알고리즘과 크루스칼 알고리즘`을 떠올렸지만
익숙한 프림 알고리즘으로 풀어보았습니다
어제 문제에 이어 오늘 문제도 `우선순위 큐`와 `comparable`을 쓰는 문제라 반복적으로 연습이 좋았습니다
이번 문제는 푸는 과정에서 딱히 어려운 점은 없었습니다.
그나마 문제를 읽을 때, 문제의 가중치 범위가 int의 최대값과 최소값까지 주어지는 것을 보고, 아 자료형으로 long을 써야겠구나 했는데 알고 보니 정답의 가중치 범위가 int 내부라는 말이어서 다시 생각을 한 순간은 있었습니다.
이번 문제 또한 이전에 풀었던 문제여서 4달 전의 제 풀이를 봤습니다.
이번에 풀면서 pq에 다음 연결된 정보들을 `넣을 때에도 방문 여부를 보고 거르는 것이 효율적일까` 고민하다가, `프림은 간선이 정점의 수보다 하나 적도록 연결하면 더 이상 탐색을 하지 않기 때문`에, 우선순위 큐에 방문했던 정점을 이은 정보들이 남아있더라도 탐색을 끝내기에, 아 `넣을 때는 안 봐줘도 되겠다 생각`하고 코드를 완성했는데,
4달 전 풀이에는 이 과정을 넣어서 시간이 조금 긴 결과가 나왔었네요.
또 성장한 저를 보니 뿌듯하네요 하핫^^
=> [BOJ] 1197. 최소 스패닝 트리💸

여아정/boj_1916.java
백준 1916문제 풀었습니다.
벨만-포드 문제라며 적힌 유형이라는 걸 알고 풀었는데 사실 그게 뭔지 잘 모르겠고 다익스트라 같아서 다익스트라로 풀었습니다.
출발점에서 도착점으로 갈 때 최소 비용을 구하는 문제길래 다익스트라구나 하고 풀었습니다.
전형적인 다익스트라 기본 유형이라고 느꼈습니다.
클래스를 생성하고, 단방향으로 출발 지점에서 도착 지점으로 갈 수 있는 인접 리스트를 생성합니다.
그리고 최소 비용을 우선으로 뽑을 수 있도록 `PriorityQueue` (이하 `pq`로 생략)를 사용했습니다.
`pq`를 이용해서 `start`지점 부터 뽑으면서 방문체크 하고, 현재 지점에서 갈 수 있는 다른 지점들을 탐색합니다.
다른 지점의 비용이 현재 지점을 지나서 가는 경로보다 더 비용이 크다면!!! 갱신해줍니다(이게 약간 dp같이 최적으로 탐색하는 거라고 합니다)
사실 초반에 많이 틀린 이유가 값 갱신은 잘만 해줬으면서 `pq`에 다음 값 넣을 때 갱신한 비용 값을 안 넣어서 틀렸습니다. ㅠㅠㅠㅠ🥲
흑 로직 잘 생각하면서 풀어봐야겠어용~
다익스트라 기본 다시 잡을 수 있어서 좋은 문제였습니다람쥥
=> [BOJ] 1916. 최소비용 구하기

soomin/BOJ_2252.java
위상정렬을 몰라서 위상정렬을 공부하고 풀었습니다.
저 어떻게 진입 차수와 연결된 노드 번호(학생번호?)를 저장할지 헤매서 중간에 자료구조 부분만 답지 참고했습니다. 
키를 비교한 정보를 받아와서 각 학생번호 별로 진입차수를 저장하고, 연결된 관계를 list에 저장했습니다.
1. 진입차수가 0인 번호를 q에 넣고 탐색 시작
2. q에서 원소를 하나씩빼서 방문하면 간선을 없애고 => 연결된 노드의 진입차수 -1
3. 연결된 노드가 또 진입차수가 0이면 q에 넣는다.
4. 2, 3을 반복한다
=> [BOJ] 2252. 줄세우기

여아정/boj_2252_줄세우기.java
2252번 줄 세우기 문제 풀었습니다.
처음에 정렬 어떻게 해야할지 몰라서 바로 위상정렬 검색했습니당..^^
1달전에 알고리즘 스터디에서 한다고 문제를 풀었는데 문제만 풀고 pr도 안적었고 다시 문제보니 다시 까마득해서
위상정렬 다시 공부하고 문제 다시 풀었습니다. 여전히 메모리 초과랑 시간초과도 맞았구여 이래저래 예외 상황 다 만나고 겨우 맞췄습니당...ㅎ
일단 위상정렬의 경우 순서가 존재하는, 사이클은 없는 상황에서 사용할 수 있는 정렬기법입니다. 그리고 답이 1개가 아니라는 특징이 있습니다. 값을 `List<Integer>[]`로 작은 값의 idx에 큰 값들을 list에 넣어줬고 초기에 input을 받을 때 마다 향하는 간선을 각각 카운팅 했습니다. 
먼저 나에게 오는 간선이 0 인 값부터(진입 차수가 0) 먼저 `Queue`에 넣었습니다. 그리고 q가 다 돌때까지 현재의 값에서 갈 수 있는 값이 진입차수가 0 일 경우 계속 q에 넣어서 위상정렬을 완성했습니다.
오랜만에 알고리즘을 다시 공부해서 가물가물한 문법 기억부터 다시 했는데 슬슬 다시 공부해야겠숨다
=> 👻[BOJ] 2252. 줄 세우기

여아정/boj_1789_수들의합.java
백준 1789. 수들의 합 문제 풀었습니다.
그 수학문제 같고 그리디 같았는데 그냥 아무생각 없이 멍하니 쳐다보다가 푸는데 좀 오래 걸린 것 같습니다. 생각보다 단순했는데 아니 그냥 완전 단순이었는데 .............................
에 일단 해당 `S`의 수를 만들기위한 서로다른 자연수의 합에 대한 문제였습니다.
결국 1부터 쭉 더 했을때 최대한 많은 수 `cnt`를 가질 수 있으므로 처음으로 `S`를 넘는 순간 `cnt-1`을 하면 됐던 겁니다람쥐......
멍청멍청....................
열심히 할게용
=> [BOJ] 1789. 수들의 합

성영준/boj_1916_최소비용_구하기.java, 성영준/boj_2252_줄_세우기.java
`구현`이라고 생각하고 풀었습니다
역시나 `위상정렬`이었습니다
`그래도 구현`으로 풀었습니다
사실 `위상정렬이란건 인지`했지만,
`이전에도 같은 위상정렬 문제`가 나와도 `제 풀이`식으로 해도 `풀리길래` 그렇게 풀었습니다
근데 지금 위상정렬 찾아보니까 그냥` 제 풀이에서 과정 중에 가중치만 넣으면 위상정렬`이더군요
촤핫^^
이전에 싸피에서 비슷한 문제를 풀었는데,
그때 제 풀이가 작은 사람 큰 사람 모두 저장하는 식이었습니다
하지만 큰 사람만 저장해도 됐던게 기억나서 그렇게 풀었습니다
감삼동그라미어켓타워싱턴~
=> [BOJ] 2252. 줄 세우기👨‍👦

전수민과_끝까지_간다/boj_2589_보물섬.java, 전수민과_끝까지_간다/boj_2667_단지번호붙이기.java
백준 실버 1 2667 단지번호 붙이기 풀었습니다.
예전에 NBA 스타 코비 브라이언트가 인대가 끊어지는 부상을 당한 적이 있었습니다. 그의 나이 33살이었습니다.
사람들은 이제 코비가 은퇴를 할 것이라 생각했습니다. 그의 에이전트도 그에게 권유했죠. 
코비는 절망했습니다. 
그는 한동안 그의 모든 좌절을 페이스북에 쏟아냈습니다.
더 이상 쏟아낼 억울함이 없을 때, 그는 이렇게 말했습니다.
'더 이상 남을 탓해서는 안된다. 모두가 힘들다. 심지어 나보다 힘든 고통을 겪는 사람들도 존재한다.
이제 다시 어깨를 펴고 앞으로 나아가야 한다. '
**'곰과 내가 싸우는 모습을 본다면 곰을 위해 기도해라'**
> 이듬해 코비는 35살의 나이로 해당 시즌 NBA 최다 MVP를 기록했습니다.
어쩌면 모든 건 자신이 생각하는 자세와 관련되어있지 않을까요? 
알고리즘, 다시 달리겠습니다.
=> [BOJ]2667.단지번호붙이기

성영준/boj_1931_회의실_배정.java, 성영준/pg_43105_정수_삼각형.java
https://school.programmers.co.kr/learn/courses/30/lessons/43105
DP라고 생각하고 풀었습니다
DP가 맞았습니다.
사실 문제 카테고리가 보여서 바로 확인 가능하였습니다.
하지만 먼저 생각했습니다.
문제를 보고 먼저 dp 배열을 따로 만들 지에 대해서 고민했습니다.
주어지는 triangle 배열에 직접 누적 값을 갱신하는 방법으로도 문제를 해결할 수 있었기 때문입니다.
하지만 원본을 훼손하는 방식으로 연습하다, 나중에 원본이 훼손되면 해결되지 않는 문제가 나올 때를 대비해 배열을 만드는 방법을 택하였습니다.
두 번째로, 그렇다면 그 때마다 길이가 다른 배열을 어떻게 초기화를 해야 하는 지에 대해서 고민을 했습니다.
오랜만에 푸니까 이런 부분도 까다롭게 느껴졌습니다.
세 번째로, 양 끝 누적 값과 사이 누적 값을 따로 계산하는 방식을 고민했습니다.
이 때, 두 값 중 높은 값을 선택하는 부분을 작성할 때, 처음에 Math.max의 존재를 잊어서 삼항 연산자를 이용하여 풀었습니다.
나중에 Math.max를 적용한 코드로 고쳤습니다.
지난번 소프티어 때 DP문제를 보고 DP인줄 모르고 다르게 풀었다가 떨어져서 아쉬웠는데, 오랜만에 푸니까 재밌었습니다람쥐
=> [PG] 43105. 정수 삼각형 🔺

전수민과_끝까지_간다/boj_2589_보물섬.java, 전수민과_끝까지_간다/boj_2667_단지번호붙이기.java
백준 2589보물섬 
BFS 거리 계산 + 브루트 포스로 풀었습니다. 
할 말이 없어서 삼행시 하고 마무리 하겠습니다. 
보 일러 버튼을 누르는 할머니 손
물 집이 터지고 주름졌지만 보드라운
섬 섬옥수
=> [BOJ]2589.보물섬

성영준/boj_14940_쉬운_최단거리.java, 성영준/boj_1931_회의실_배정.java
`bfs`라고 생각하고 풀었습니다.
오랜만에 그래프 탐색 문제 하나 찾아서 풀었습니다.
보자마자 bfs라는 건 인지했습니다.
근데 오랜만에 풀어서 쓰는 게 좀 생소했습니다.
맨 아래 에러는 제가 처음 그래프 탐색을 할 때, `방문체크로 고민하던 그대로 틀렸습니다`.
`값을 넣는 타이밍`을 자료구조에 넣을 때 해야 하는지, 뺄 때 해야 하는지 였는데, `넣을 때 해야` 같은 탐색 단계에서 중복을 피할 수 있기 때문에 넣는 순간에 해줘야 합니다.
덕분에 이제 기억에 오래 남을 것 같습니다.
그 다음부터는 불필요한 입력 과정, 탐색 과정과 변수를 줄이며 시간을 줄였습니다.
원래 이 과정은 풀기 전에 생각을 잘 해서 코드 작성 후 고치는 일을 줄여야 하는데 오랜만에 푸니 좀 미숙했네요.
다음엔 수정 과정을 줄여보겠습니다람쥐~
=> [BOJ] 14940. 쉬운 최단거리 📏

성영준/boj_16928_뱀과_사다리_게임.java, 성영준/boj_1931_회의실_배정.java
'`dp`문제네? 오랜만에 dp로 풀어야지~'하고 어느샌가 `bfs`로 풀었습니다
dp 문제인 줄 알았습니다.
소프티어의 영향이 컸나 봅니다.
와중에 dp로 풀겠다 하고 bfs로 풀었고,
함수 명은 dp가 아닌 db로 해서 풀고 있었습니다.
먼저 `뱀과 사다리를 따로 준 이유`에 대해 생각했습니다.
문제를 읽으면서 생각한 풀이는 구분 없이도 가능한 풀이였는데, 괜히 나눠서 주니까 뭔가 있을까 하고 좀 더 생각해 보았습니다.
하지만 오히려 뱀의 경우 뛰어넘도록 일부러 `함정을 판 것이라 판단`했습니다.
예를 들어 2 -> 90 50 -> 99 사다리가 있고, 91 -> 49 뱀이 있으면 뱀을 이용하는 방법이 더 좋기 때문입니다.
두 번째로는, 그럼 `어떻게 뱀과 사다리 정보를 저장하고 이걸 활용할 지`에 대해 생각했습니다.
먼저 한 자료구조를 선언할 때, `여러 정보를 가진 class를 저장하도록 하고, 그 자료구조의 flag를 읽어서 이동 여부를 판단` 해야 하는지 생각했습니다. 하지만 이 경우 너무 `복잡`하기도 하고, `오래 걸릴 것` 같아서 포기했습니다.
그 다음으로 생각한 방식이 지금 방식인데, `따로 뱀과 사다리 정보를 저장하는 자료구조를 선언`하고 이동을 할지 말지 판단하도록 했습니다.
중간에 한 번, input값을 String으로 변환하는 시간을 줄이려 괜히 시도했다가, 후반에 next가 int로 저장되어 호출에 문제가 있다는 걸 인지하는데 오래 걸렸습니다. 디버깅 오랜만에 하니까 좀 헷갈리네요 유유
=> [BOJ] 16928. 뱀과 사다리 게임 🐍

성영준/boj_1931_회의실_배정.java, 성영준/programmers_164673_조건에_부합하는_중고거래_댓글_조회하기
https://school.programmers.co.kr/learn/courses/30/lessons/164673
날짜 변환 및 비교, 조인, 정렬 등 기초적인 내용을 모두 물어보는 문제입니다.
수, 토 마다 sql 낭낭하게 올리겠습니다
생각보다 sqld 짬이 있어서 그런지 조인문과 정렬은 쉽게 했습니다
근데 날짜 때문에 계속 애를 먹었습니다
date_format과 date문 두 개 다 사용법 익혀봤습니다
근데 date_format이 더 깔끔하다 생각이 듭니다
sql 해보니 재밌네요
=> [PG] 164673. 조건에 부합하는 중고거래 댓글 조회하기

성영준/boj_1931_회의실_배정.java, 성영준/programmers_42628_이중우선순위큐.java
`우선순위큐`라고 적혀있었습니다.
적혀 있어도 어려웠습니다
이 문제는 `q 2개 써서 풀라고 만든 문제` 같은데, `비효율적이라 생각`이 들어 `다르게` 생각해 봤습니다
`자료구조를 하나만 써서, 맨 앞,  맨 뒤 값을 컨트롤 하는 것`입니다
이를 하려면 자료구조가 정렬 상태를 유지해야 가능한데, `Arrays.sort를 쓰지 않았습니다`
약간 저 B형 딸 때처럼 풀었는데, 이진 탐색으로 위치 찾고 넣는 방식입니다
이게 아마 저 B형 때도 비슷한 느낌의 문제가 나왔었는데, sort를 쓰는 것 보다 직접 `이진 탐색을 하고 넣는 것이 더 빨랐습니다`
왜냐하면 이진 탐색은 모든 값이 잘 있나 확인하는 과정도 있기 때문입니다
근데 기억이 났지만, 어떤 자료구조에서 했는지 기억이 나지 않아서 고민 좀 하느라 시간이 걸렸습니다
첫 번째 사진이 제가 작성한 코드로 제출 했을 때고, 두 번째 사진이 `GPT`가 제 코드보다 저게 더 빠르다! 하고 준 코드였는데 `제가 이겼네요` 역시 아직 ai는 인간을 이기긴 부족해 보입니다 하핫
=> [PROGRAMMERS] 42628. 이중우선순위큐 2️⃣

성영준/boj_1931_회의실_배정.java, 성영준/pg_157343_특정_옵션이_포함된_자동차_리스트_구하기
아마 like문 쓰는거 해보라는 문제 같습니다
맞구요 쉽네요
컷!
근데 order by desc 이거 좀 기억 잘 안 나네욘사마
=> [PG] 157343 특정 옵션이 포함된 자동차 리스트 구하기

성영준/boj_1931_회의실_배정.java, 성영준/pg_12927_야근_지수.java
https://school.programmers.co.kr/learn/courses/30/lessons/12927
그리디라고 생각했습니다.
그런데 제 풀이는 효율면에서 실패라고 계속 떠서 풀지 못했습니다.
정석 풀이는 더 이해가 안 됩니다 유유
그리디인건 예시가 친절하게 나와 있어서 파악하기 쉬웠습니다.
그래서 보자마자 이건 백준의 나무 자르기였나 그런 비슷한 문제가 있는데 그거와 같은 풀이다 라고 생각했습니다.
싸피 초반에 알고리즘 스터디를 할 때 차센세랑 그 문제를 풀면서 서로 다른 풀이가 나왔는데 같은 시간이 걸려서 코드 가지고 한참 애기 한 기억이 있었습니다.
그때 제 풀이는
1. 모든 나무를 높은 순으로 정렬
2. 같은 높이의 나무를 묶어서 다음 나무와의 높이 차를 구함
3-1. 요구하는 목재량을 채울 수 있다면, 해당 나무 내에서 해결
3-2. 요구하는 목재량을 채울 수 없다면, 해당 나무 묶음의 높이를 다음 나무 높이까지 자름
1~3 반복
였습니다.
차센세 풀이는 제 기억으로 이진 탐색으로 풀었는데, 같은 속도에 풀이가 훨씬 간결한 게 기억이 났습니다.
그런데 아무리 생각해도 이진 탐색을 활용한 풀이는 기억나지 않아서, 제 풀이 말고 다른 방법이 뭐가 있을까 하고 풀었는데, 제 풀이에서 2번 과정이 빠진, 다음 나무와의 높이 차가 아니고 1만큼 자르는 식으로 다시 풀어보았습니다.
그런데 해당 풀이로는 효율면에서 실패라는 판정을 받아서 한참 고민 후에 다른 사람의 풀이를 보았습니다.
그게 지금 위에 성공한 결과의 코드인데,
1. priorityQueue에 일을 넣어 작업량이 높은 순으로 정렬
2. …
=> [PG] 12927. 야근 지수 😪

성영준/boj_1931_회의실_배정.java, 성영준/pg_164672_조건에_부합하는_중고거래_상태_조회하기
날짜 데이터 형식 맟추기
스칼라 표현식 연습하기 라고 생각하고 작성했습니다
물론 답지 봤습니다
스칼라는 case when then end 쓰면 되더군요
날짜 데이터 포멧 변환은 또 생각이 안 났습니다
그래서 둘 다 답지 보고 했습니다 
어려웡~
=> [PG] 164672. 조건에 부합하는 중고거래 상태 조회하기 🥕

성영준/.gitignore, 성영준/boj_1931_회의실_배정.java, 성영준/pg_43163_단어_변환.java
https://school.programmers.co.kr/learn/courses/30/lessons/43163
`bfs라고 생각`하고
탈출조건 많이 넣어서 `backtracking`으로 풀었습니다
문제 보자마자 머리가 띵했습니다
이런 문제를 보면 꼭 단어를 `전부 훑으면 안 될 거 같은 기분`에 찝찝합니다
`비트를 활용`할 순 없을까
한참 생각 후 `없다고 생각`했습니다
있다면 가르쳐주세요 배우고 싶습니다
그 다음으로 `매번 탐색이라도 줄이자` 생각했습니다
매번 탐색마다 단어를 확인 할 필요 없이, `미리 비교해둔 리스트`를 만들면 되지 않을까 생각했습니다
단어 길이가 최대 10개, 단어 수의 최대가 50개로 매번 탐색하면 별로 일거라 생각했습니다
오랜만에 B형 치듯 모듈화 야무지게 한 코드가 나왔네요
뿌듯합니다람쥐며느리어카~
=> [PG] 43163. 단어 변환 🔁

성영준/boj_1931_회의실_배정.java, 성영준/pg_42898_등굣길.java
`dp` 글자를 보고야 말았습니다
그런데 감이 안 와서 비슷한 문제의 `풀이를 참고`했습니다
보니까 `원래 생각한 풀이`가 맞았는데,
생각보다 풀이가 `너무 쉬워서 의심`을 했습니다
자꾸 `틀린 이유`는 맞게 했는데 `오타` 및 사소한 `실수`(더하고 나누기를 나누고 더하기 했음)였습니다.
그런데 코드 오류인 줄 알고 한참 봤습니다
역시 `IDE를 안 쓰고 하니까` 저런 부분이 자꾸 걸리네요
IDE 안 쓰고 푸는 연습 많이 해야겠습니다
그리고 dp 많이 풀어봐야징징이~
=> [PG] 42898. 등굣길 🚶‍♀️🚶‍♂️🏃‍♀️🏃‍♂️

성영준/boj_1931_회의실_배정.java, 성영준/boj_2293_동전1.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1zu6qQYWyNqa4l1CYP6eNUSmphg0N0%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2FCkol2)
dp라 생각이 들었습니다
예상한대로 군무이탈체포조 맞았습니다
소프티어 3번, 네이버 3번
아주 dp 난도질 당하고 벼르고 있었는데 잘 걸렸네요
dp 특 memorization 바로 생각하고 어떻게 적용할 지 머리 좀 굴렸습니다
굴리다 보니 그냥 새로운 동전 나오면 크기만큼 뺀 방법 수를 더하면 되더군요
그래서 입력 받는 순서대로 바로 투입 시키면서 크기만큼 뺀 자리 수를 더했슴다
내일도 dp 나오면 부수겠슴다ㅋ
i mak'it look EZ~
=> [BOJ] 2294. 동전 1 🪙

성영준/boj_1931_회의실_배정.java, 성영준/boj_2667_단지번호붙이기.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19zhNCRQTkAJQBjkCCvC6GGpHAZ1NEwtvs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=o0TZFAN)
오랜만에 보는 귀여운 `bfs` 문제~
정답이구연~
일단 앞으로 문제 보자마자 생각 적는 노트를 켜놓고 적어야겠슴다
제가 적은 내용은
```
1. 2부터 시작하기
2. 0으로 바꾸기
3. 방문 체크하기
4. pq에 넣고 빼는게 젤 좋은가
5. 입력에 띄어쓰기 없으니까 char로 배열 둬야겠다
6. 그럼 2번이 젤 좋네
1은 integer로 변환해야함
3은 메모리 더 안 좋음
```
이겁니다
1~3번은 문제만 읽어봤을 때 접근 방법 생각해 봤습니다
`1번 방법`은, `1부터 시작 하면 다음 1번들 모두 방문했다고 착각`할 테니
이 문제는 집 번호 붙이는 건 내 마음이니까 `2부터 붙이고` 1 이하일 때 continue 하면 되려나 했고요
`2번 방법`은, 그럼 `방문한 집 모두 0으로` 바꾸면 안 좋은가 생각했습니다. 그럼 0일 때는 무조건 넘기고 1이 나오면 0으로 바꾸면 되지만, `뭔가 바꾸고 이런 게 오래 걸릴까` 한다면, 제가 1학기 때 이거도 연구했었는데, `변수 값 바꾸는 건 시간 그냥 없다고 생각해도 됩니다`
`3번 방법`은, …
=> [BOJ] 2667. 단지번호붙이기 🪧

성영준/boj_1931_회의실_배정.java, 성영준/boj_4386_별자리만들기.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19ZopxRcA9xHPJoPAJsQLB8tEYfy96s8I%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=A008mMb)
소프티어 치기 전 `프림 알고리즘` 풀고 싶어서 위상정렬 인지하고 풀었습니다.
하지만 so sad
계속 틀렸당나귀
패착 1 난 프림만 아는 바보다 `이건 크루스칼이 더 좋다`
패착 2 `소프티어 치기 직전` 급한 마음에 서둘러 쓴 코드
패착 3 또 `요새 알고리즘 안 풀어서` 최고 투박한 코드
패착 4 오랜만에 본 `유리수와 소수점 컨트롤` 문제
패착 5 프림 알고리즘 다소 `아쉬운 디테일`
프림 하나만 바라보고 풀려니까
이게 0번 고정하고 할 때, 0번에서 팔 `하나 더 뻗어 나갈 수 있는 건데`
그 경우 고려 못하고 자꾸 `방문체크 해놔서` 엄청 틀렸습니당나귀 ㅠㅠ
1. `노드`랑 `엣지` 클래스 먼저 만들기
2. 사이 거리 `인접 그래프`로 `priority queue`에 넣기
3. `프림` 돌리기
이렇게 풀려고 했고 해냈습니다
오늘 소프티어 기분 좋게 풀었으니 참겠습니다
감3다
=> [BOJ] 4386. 별자리만들기 💫

성영준/boj_1931_회의실_배정.java, 성영준/boj_2294_동전2.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19T8wHR1YxAlF0lbsyEsVXSJtcSc7FJfhs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=zEONRO6)
`dp인가 배낭인가 하다가 dp`로 풀었슴다
`배낭은 아니었슴다`
이유1. 배낭은 알고 보니까 `최고 가치`가 돼야 한다
이유2. 배낭은 한 종류의 원소를 한 번만 사용 가능하다
그래서 dp로 한 게 맞았슴당나귀
문제 보자마자 동전1이랑 비슷하게 생각해 봤는데
암만 봐도 최소보다 안 될 경우 -1 출력하라는 게 너무 어려웠습니다
그래서 그림 그리면서 이래저래 풀어봤는데
해당 가치부터 1로 시작하도록 하고
해당 위치에서 가치 만큼의 이전 위치와 비교해서 더 작은 값을 넣도록 해야 하는 건 파악했습니다
근데 만약 2랑 3만 있을 때, 두 수 모두 7을 못 만드는데
2 2개에 3 1개면 7이 만들어지니 배수만큼 움직여야겠네 라는 생각은 금방 저물었습니다
이거 때문에, 그럼 지금 가치 수의 배수로 도달 못해도 해당 위치에 값을 넣어야 하니까, 맨 마지막 도착지가 -1이 나오게 하는 거 생각하는게 좀 걸렸습니다
그러다 전부 그냥 최댓값 채우고 비교하는거 떠올리고 풀었습니다
틀린 건 문제가 불친절해서 틀렸습니다
보통 목표보다 큰 동전은 잘 안 …
=> [BOJ] 2294. 동전2 🪙🪙

성영준/boj_1931_회의실_배정.java, 성영준/boj_2589_보물섬.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1M97974tIRMpGy9kRXzWpsbjrhMRo69uM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=OMfXs8L)
`bfs 완탐을 인지`하고 그렇게 하지 않았습니다
왜냐하면 효율을 따지고 싶었습니다
`bfs 덜탐`으로 풀었습니다
30분만 풀고 자야지는 어느세 3시간 30분이 지났고
노력의 결실은 3등이라는 결과를 가져왔습니다 호호루~
```
1. `완탐 + bfs` 가 먼저 생각나는데 이렇게 하기 싫다
갔던길 표시했으니까
2. `땅 한 군데 도착했을 때, 거기서 가장 먼 지점에서 다시 출발`하면 그게 젤 먼거리 아닐까
2-2. 그럼 처음엔 방문체크용 배열로 재방문 막고, 다음엔 지나간 곳 물로 채우면 재방문 막지 않을까
2-3. 함수 재사용 하고 싶으니까 처음에 방문체크도 문자 새로 채우면 재사용 가능하겠다
3-1. `한 지점으로 부터 시작해서, 더이상 갈 곳 없는 애들`을 모은다
3-2. 그 리스트만 돌면서 계산한다
4. `길모퉁이`를 전부 모으자
```
오늘도 첨부하는 생각주머니
1. 먼저 `완탐`의 경우입니다
그런데 `'만약 코테였다면' 이라는 접근으로 절대 완탐으로 안 풀어야지` 하고 심술났습니다
그럼 제가 할 일은 뭐냐
한 땅에서 찾는 횟수 …
=> [BOJ] 2589. 보물섬 💎

성영준/boj_1931_회의실_배정.java, 성영준/boj_5430_AC.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19ZbyGE2WBL1wIChYer9TuWIDx2oBy5G5E%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MiR9tQW)
`Deque라고 인지`했습니다
`그렇게 풀기 싫었`습니다(사유: Array Queue는 삽입 제거하는게 느리기에 싫다)
`구현`으로 풀었습니다
이렇게 삽질 오래한 문제도 오랜만이네요
오늘은 금방 풀겠거니 하고 메모장 작성 건너뛰고
삽질 많이해서 더듬더듬 써보겠습니다
1. `투포인터 비슷하게 풀자`
Deque 쓰기 싫어 심술 먼저 났습니다
다른 방법 없을까 하고 생각하다 보니
그냥 deque 쓰듯이 D 나올 때, R 나온 횟수에 따라 왼쪽, 오른쪽 포인터를 가운데로 옥죄어 오면 되겠구나 하고 풀었습니다
사실 1.이 끝이긴한데 삽질한 구간 나열이 낫겠네요
[1,2,3,4] 이렇게 들어오는 데이터를 어떻게 자를까
1. `replaceAll을 쓰자`
이런게 늘 뇌절옵니다
저는 옛날에 연구를 통해 split이 매우 느린 친구임을 인지하고 있었기에 절대 안쓰려 10분 삽질했습니다
그래서 먼저 '아, 그냥 나머지 다 ""로 변환하면 되겠구나' 하고 replaceAll을 하는데 자꾸 `[` 이거를 바꿀 문자로 넣으면 코드에 에러가 자꾸 떠서 한참 …
=> [BOJ] 5430. AC 😡

성영준/boj_1038_감소하는수.java, 성영준/boj_1931_회의실_배정.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1K7Hy0oSP5qFmTzIHPVYTKJwlZ5lIEJI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=zulfTlR)
도저히 생각 안 나서 그냥 완탐으로 했습니다
하지만 틀려서 답지 봤습니다
조합이었습니다
생각이 진짜 제 머릿속 풀이를 코드로 하려고 했지만 절대 못하겠어서 답 봤습니다 유유
1. combinations 함수 사용 ➡️ 중복을 제외한 조합
combinations(list, n) : list 중에서 n개를 조합
2. for 문을 중첩해서 사용
➡️ (0) 부터 (0,1,2,3,4,5,6,7,8,9) 까지의 조합을 만듦
3. 만든 조합(배열)을 거꾸로 정렬 후 문자열로 만듦
➡️ '0'부터 '9876543210'까지의 문자열 만듦
4. 만든 숫자를 int 타입으로 캐스팅해서 리스트에 저장
➡️ 0, 1, 10, 2, 20, ... 의 순서
5. 리스트를 정렬
➡️ 0, 1, 2, 3, 4, ... , 9876543210 의 순서
이렇게 한 답을 봤습니다..
너무 어려웠습니다..
이런 문제가 늘 젤 어렵습니다..
=> [BOJ] 1038. 감소하는 수 📉

성영준/boj_14500_테트로미노.java, 성영준/boj_1931_회의실_배정.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1AuqUNFOs1embvisphuuQepeyuHst8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Hku7d-c)
dfs로 풀었습니다
dfs 3번하고 1번 둘레 보는 게 완전 싸피 A형 문제네요
오랜만에 풀어서 재밌고 쉬웠는데
시간 줄인다고 고생 좀 했습니다
김머영 컷^^
=> [BOJ] 14500. 테트로미노 🟥🟨🟩🟦🟪

성영준/boj_17219_비밀번호찾기.java, 성영준/boj_1931_회의실_배정.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1rg2T5ui0iIWIjlLDqKZuB3RTt2N1hk8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=kPG64DB)
너무 쉬운 map 문제~
여기에 올라온 문제는 다 풀어봤길래 solved.ac에 class 3 다 풀어보려고 젤 쉬운 거 풀었습니다람쥐~
there's nothing to say
=> [BOJ] 17219. 비밀번호 찾기 🗝

성영준/boj_1931_회의실_배정.java, 성영준/boj_2579_계단오르기.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19ROI0NWkP3vZWegwJj54HXoKvR5h4M%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=4OjOZT3)
디피같아 보였는데 디피 아닌가 했는데 디피로 풀었습니다
실버 3이라고 얕봤는데 생각보다 까다로웠습니다
근데 풀고 보니 별거 없네요
so easy~
=> [BOJ] 2579. 계단 오르기 📈

차성원/boj_1700.java, 차성원/boj_1806.java
그리디라고 생각은 했는데 못풀어서
접근방식 구글링 참고했습니다
오랜만에 알고리즘 하려니까 힘드네요.
그리디 생각은 했는데도 효율적으로 검사하는 로직을 생각못했습니다.
머리가 굳었나봐요.
다시 열심히 하겠씁니다.
=> [BOJ] 1700 멀티탭 스케쥴링

.gitignore, soomin/BOJ_20922.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19UgMTMubnTmf0ArQPW2DNuOpcOKZjo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MhoclOr)
일단 보고 최장을 구한다... 그리고 조건이 있다 흠... 투포인터인가 했슴다
로직은 음 start와 end 두개의 포인터를 두고 
end를 가능만큼 증가시킵니다. 여기서 가능한 만큼은 같은 원소가 k개 이하인 것입니다람쥐 그래서 원소가 몇개 포함되어 있는지 카운트할 배열을 만들엇습니다.
end를 최대한 증가하면 길이를 저장하고 start를 증가시킵니다. 그리고 다시 end를 증가합니다. 처음에 이 부분을 단순하게 생각하고 start를 증가시키면 end도 start값으로 바꿔주었는데요 
그렇게 할 필요가 없는게 최장을 구하는 것이기 때문에 이미 start를 증가시키면 증가시키기 이전 길이보다 무조건 1개 작기 때문에 그렇게 할 필요가 없슴다. 고려할 필요가 없슴다 예... 히히루
고생하셨슴다.
=> [PG]20922. 겹치는 건 싫어 👎👎👎

.gitignore, soomin/BOJ_1202.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1KVxPR2KA5NRUZ2ukL780Kxk8rVYo4z0U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=aFXdVB-)
우하하 오늘 셤보고 비슷한 유형을 풀어봤습니다. 그리디와 우선순위 큐를 사용해서 풀었습니다.
각 원소를 어떻게 정렬해야할지 결정하는게 좀 힘들었습니다. 
처음에는 우선순위 큐에 입력받는 보석들의 정보를 바로 집어 넣어서 가방에 가장 가치가 높은 순으로 집어 넣으려고 했는데 가방에 단 한개의 보석을 넣을 수 있었습니다.
그래서 보석을 저장하는 배열, 가방의 무게 배열, 특정 가방에 넣을 수 있는 보석들을 저장하는 우선 순위 큐 이렇게 저장했습니다.
1. 보석의 저장하는 배열 (입력) => 무게 기준으로 오름차순, 같으면 가치가 큰 순서로 내림차순
2. 가방의 무게 => 오름 차순
3. 우선순위 큐 => 보석의 가치로 내림차순 ( 여기에 저장 되는 건 하나의 가방에 들어갈 수 있는 보석들이니까 그중에서 가장 가치가 큰 보석을 뽑기 위함입니당)
이렇게 정렬하고 가방의 무게를 보면서 각 가방에 들어갈 수 있는 가장 가치가 큰 보석을 구했습니당
dp로도 풀 수 있는지 고민 더 해볼게용
그리구 3%에서 계속 틀려서 고쳤는데 알고보니까 이게 데이터 …
=> [BOJ]1202. 보석도둑 💎

여아정/boj_7569.java
BFS 문제입니다.
정말 단순 BFS 문제입니다. 근데 너무 오랜만에 BFS 하니까 어떻게 하더라 하면서 엉금엉금(?) 했습니다.
3차원 BFS 탐색이었습니다. 6방탐색으로 (위, 아래, 오른쪽, 왼쪽, 윗층, 아래층)으로 탐색이 가능합니다.
그리고 `deque` 활용해서 그냥 돌렸습니다.
초기 작업으로 전체 토마토 개수를 구하고, 초기에 익은 토매토 개수 두개를 활용하여 bfs 를 돌면서 존재하는 모든 토마토가 익었을때 그때의 day를 출력하도록 했습니다.
그리고 모든 토마토가 익을 수 없는 경우는 -1로 출력하도록 했습니다.
=> [BOJ] 7569. 토마토🍅

성영준/boj_29160_나의FIFA팀가치는.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18eOBUf6VxiZe7MLrvjRrszA80I2S3khZA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-fdtr5X)
정렬과 pq를 이용한 풀이를 먼저 생각했습니다
하지만 pq를 이용하는건 비효율적이라 생각하고 이진 탐색을 추가로 생각했습니다
문제 보자마자 든 생각은 pq 쓰면 풀리겠네 였습니다
근데 예전 나무 자르기('https://www.acmicpc.net/problem/2805') 문제와 유사해 보였기에 해당 풀이를 좀 생각했습니다
이 문제를 차센세는 이진탐색을 이용했었고
저는 저만의 풀이를 이용했었는데 속도차이가 얼마 없었던 기억이 나서 이진탐색을 적용해보기로 했습니다
하지만 pq로 먼저 풀어놓고 개선하고 비교하고 싶어서 pq로 먼저 쉽게 풀었습니다
그 다음 이진탐색을 이용한 풀이를 적용했는데
int를 long으로 안바꿔서 2시간 날렸습니다 ㅠㅠ
근데 풀고 나니 이진탐색 풀이가 더 느렸습니다
진짜 이해가 안되는데 지금 시간이 늦어서 내일 마저 분석해 보겠습니다
님들도 분석하고 피드백 좀
진짜 한참 고민하고 찾아보고 gpt한테 물어봤는데 납득이 안됩니다 유유
=> [BOJ] 29160. 나의 FIFA 팀 가치는? ⚽💲❓

여아정/boj_3190.java
[[백준] 3190. 뱀](https://www.acmicpc.net/problem/3190)
구현입니다
그냥 구현입니다.
근데 뱀이 길이 변화도 있고 해서 뱀이 존재하는 곳들을 큐에 넣어서 관리 했습니다.(삭제 편리 하도록)
그리고 뱀이 존재하는 위치를 2차원 배열에 체크 해두고 벽에 가거나 뱀 있는곳 오면 끝나도록 했습니당
=> [BOJ] 3190. 뱀 🐍🐍🐍

여아정/boj_1922.java
최소스패닝트리 문제입니다.
우선순위큐를 활용하여 풀었습니다.
문제 보고 바로 최소스패닝트리라고 생각했습니다.
비용 오름차순으로 정렬하는 것으로 우선순위큐를 정렬했습니다.
최초의 1번 노드에서 시작하여 1번 노드에서 갈 수 잇는 경우를 우선순위큐에 넣습니다.
그리고 방문한 노드에 대해 체크를 합니다.
이를 계속 반복하며 방문하지 않은 노드를 최소의 비용으로 가게 합니다(?)
오랜만에 풀었는데 기억더듬으면서 생각할 수 있어서 좋았습니다.
문제 추천 해 준 김수만두씨 감사합니당
=> [BOJ] 1922. 네트워크 연결 🛜

성영준/boj_9461_파도반수열.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1rEXq30kPMrIION7CkkVRBQKfBkyY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=5W8syN0)
간단한 메모라이징 문제라 생각했습니다
간단한 규칙성 문제였습니다
해당 자리에서 -1의 자리와 -5의 자리 값을 더하면 되는 문제였습니다
2가지 방법으로 풀었습니다
먼저 last를 두는 for문 방식입니다.
1. 현제 입력 수가 last보다 작으면 (현재 메모 배열에서 입력 수의 값이 있으면) 출력
2. 높다면 last부터 입력 수 까지 for문을 순회하며 값을 채움
그게 마지막 2번 제출 제외한 풀이입니다.
처음 에러는 1부터 100까지 단순 더하면 5050이니까 2147483647보다 작으니 int해야겠다 했는데 잘못 생각한 거였습니다
두 번째 풀이는 재귀문을 이용한 방식입니다.
for문이 된다면 재귀문이 된다는 사실을 잊고, 나보다 빠른 사람들은 어떻게 풀었을까 풀이를 보다가 발견했습니다
1. 현재 입력 수의 값이 있으면 반환
2. 없다면 -1과 -5의 재귀를 호출
3. 1부터 반복
이러면 굳이 last를 둘 필요 없어서 깔끔해 보였습니다
재귀문은 늘 거부감 들어서 멀리했었는데 오랜만에 보니까 재밌네요
=> [BOJ] 9461. 파도반 수열 🌊

성영준/boj_11727_2xn타일링2.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1WHqi1RkfzGvQXod9SpCEV7zQACOpTwgc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=G0rZqbD)
dp라고 생각하고 풀었습니다
일정이 바빠서 급하게 푸느라 디테일 놓치고 쭉 진행해서 계속 틀렸습니다
처음엔 *2가 아니고 +2구나 하고 잘 못 생각하고 한참 걸렸습니다
그러다 *2임을 깨닫고 해당 값을 넣고 제출했는데
+2일 경우 맞는 전처리와 설정값들이 저 수 많은 오류를 가져왔습니다
dp 어렵당나귀 ㅠㅠ
=> [BOJ] 11727. 2xn 타일링 2 🔲🔳

성영준/boj_17626_FourSquares.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1dlFXw35VL834RkicEutXMEF8JO86Lbqo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=YxeDaAz)
dp라고 생각하고 풀었습니다
이게 어떻게 실버 3인지는 모르겠네요
0.5초 보고 엄청 쫄았습니다
얼른 시간복잡도 계산하는 법을 배워야겠어요
이거 암만봐도 dp다라고 생각하고 나서 그냥
어떤 수에서 한 제곱수를 뺐을 때 값이 작으면 되겠다 생각했습니다
아마 문제에서 최대 4번이란 말이 없었으면 이거 못 풀었을 거 같습니다람쥐렁이
쏘 하드 ㅠㅠ
=> [BOJ] 17626. Four Squares 4️⃣

성영준/boj_1389_케빈베이컨의6단계법칙.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1bE0jOxGTn3w3C293iUbH0vrXKX0sNo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=fN-4M2C)
다익스트라라고 생각했는데 풀이는 그냥 bfs였습니다
근데 플로이드 워셜이네요
이거 지난번 소프티어 2번이었는데 유유
// 친구 연결 관계를 낮은 수 부터 시작
// 만약 내가 지금 보는 사람이 낮은 사람이라면
// 그 사람은 더 탐색 안 하고 그 사람의 친구 관계만큼 +
이거 먼저 쓰고 시작했습니다
문제가 실버 치고 생각보다 어려워서 좀 당황했습니다
토스 시험 전에 3문제는 풀고 가고 싶었는데
이거 하나 푸는데도 2시간은 넘게 걸렸네요
저만의 풀이 방식을 적용하려는 데, 잘못된 알고리즘을 떠올려서 더 오래 걸린 것 같습니다
그래서 먼저 제 풀이 방식 보다
오래 걸리는 방식 먼저 제출하고
나중에 적용시켰습니다
근데 아직 남은 부분이
먼저 지나간 수가 높고
뒤에 도착한 수가 낮으면
먼저 간 수를 더 탐색할 필요가 없는데
너무 오래 걸려서 일단 여기서 멈췄습니다
아쉽네요
누가 해줭~
=> [BOJ] 1389. 케빈 베이컨의 6단계 법칙 👩👨🧑👧👦🧒

성영준/boj_5525_IOIOI.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19Vctgk3cwdAqC26y6xoIJhsnYWSm8oiw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=AQrZl9w)
그리디와 가깝게 푼 거 같습니다
먼저 I를 확인하고
그다음 O I 패턴이 반복되는 지 보려 했습니다
그런데 n이면 IOI...OI고 그 다음 OI만 반복되면 +1하면 되므로
I먼저 보고 OI를 n - 1번 반복되는 지 확인한 후
OI가 반복되는 횟수만큼 더하게 구현했습니다
그리고 index 값을 두어서 패턴이 깨진 경우 해당 index부터 뛰어넘어 보도록 했습니다
틀린 경우는 O가 나와야 할 때, I가 나와도 index를 한 칸 뛰어 넘게 해서 틀렸습니다
코드 뭔가 깔끔한 게 마음이 편하네요
=> [BOJ] 5525. IOIOI 1️⃣0️⃣1️⃣0️⃣1️⃣

성영준/pg_59043_있었는데요없었습니다
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1saLG76EAPtAJVLFVQLzg1I54JufITwI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=akPDHGT)
https://school.programmers.co.kr/learn/courses/30/lessons/59043
join이랑 order by 연습 하는 문제 같았습니다 
오랜만에 농협 코테 앞두고 sql 풀었습니다
쉬운 코드인데 풀고 나니까 뭔가 뿌듯
as로 alias 달고
using으로 on 대체하고
order by쓰고 풀었습니다람쥐
=> [pg] 59043. 있었는데요 없었습니다 ⭕❌

성영준/pg_131113_조건별로분류하여주문상태출력하기
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19pjRL0nd7wY3Vv7ZWDct5Z6VBvI0HY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=OPtY9Cb)
https://school.programmers.co.kr/learn/courses/30/lessons/131113
case문인건 알았지만 작성하지 못했습니다
date_format인건 알았지만 작성하지 못했습니다
위에 그대로입니다
저게 다인 문제였는데 저거 다 못해서 적을게 없네요
외우고 시험쳐야징징이
=> [pg] 131113. 조건별로 분류하여 주문상태 출력하기 🚛

성영준/pg_59411_오랜기간보호한동물(2)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19Ayrculb7RcfiJXGcLVcObuuQ2O6Hh68%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=C6seySb)
https://school.programmers.co.kr/learn/courses/30/lessons/59411
또 join문제였습니다
datediff를 몰라서 틀렸습니다
그래도 join은 맞췄습니다
=> [pg] 59411. 오랜 기간 보호한 동물(2) 🐇💏

성영준/pg_42890_후보키.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1i0CbD6sGfX9YyLVVSEfIdjAxs6ILKOw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=5PojN9_)
`조합`과 `스택`을 이용한 문제라고 생각하고 접근했고,
조합 할 줄 몰라서 `백트레킹` 식으로 하다가,
`비트마스킹` 떠올리고 적용해서 풀었습니다
오랜만에 푸니까 import부터 초기화에 간단한 내부 메서드까지 다 까먹어서 진짜 오래 걸렸습니다.
심지어 레벨2 치고 너무 어려웠습니다.
틀린부분은
1. **튜플 그 자체가 식별자인 경우**
'relation의 모든 튜플은 유일하게 식별 가능하다.(즉, 중복되는 튜플은 없다.)' 라는 조건을 잘 봤는데 오히려 아니라고 생각하고 풀었습니다.
2. **후보키 원소가 중복되는 경우**
이거 때문에 진짜 오래 걸렸는데
만약 후보키가 0이면 0, 1 조합은 안 되는 게 맞지만,
후보키가 0, 1 조합이면 0, 2 조합은 되는 상황인데 그냥 0, 1 둘 다 다음 탐색에서 제외해서 틀렸습니다.
그래서 2번 방식의 풀이를 어떻게 구현하면 좋을까 떠올리다
비트마스킹 떠올리고 적용했습니다.
2시간 20분 동안 풀었네요
비트마스킹은 좀 기억 안 나서 예전에 달이 차오른다 가자 문제 보면서 참고 좀 했습니다. …
=> [pg] 42890. 후보키

성영준/boj_1918_후위표기식.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1Vt6g0GNFo1IDAwfA7x7c6LKFbcOT6w8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=gaRyMVG)
스택이라고 생각했습니다
생각보다 너무 어려웠습니다
다 풀고 나니 대학교 때 트리로 만들어서 푼 기억이 나네요 트리로 풀어볼 걸 그랬습니다
근데 일단 stack부터 생각하고 냅다 접근했습니다
처음에는 연산자와 피연산자 모두 stack에 넣고
더하기 빼기가 나오면 이전의 계산식을 다 진행한다!
라고 했는데 완전 잘못된 접근이었습니다
오히려 반대로 연산자만 stack에 넣고
피연산자는 바로바로 출력하며
무슨 연산자가 나오든 계산식을 진행하되
곱하기 나누기의 경우 곱하기 나누기만
더하기 빼기의 경우 괄호 제외 전부 진행하는 식으로 풀이했습니다
말은 쉽지 1시간 8분 걸렸네요 ㅠㅠ
코테 나왔으면 떨어졌을 것 같습니다 아쉽네요
더 열심히 해야징징이~
=> [BOJ] 1918. 후위표기식 ➕➖✖️➗🌘🌒

성영준/pg_72412_순위검색.java
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX17myuR1vlBi3Pdd54E1fT2ciPdqyDQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=UQMTpXU)
https://school.programmers.co.kr/learn/courses/30/lessons/72412?language=java
`비트 마스킹`과 `정렬`, `이진 탐색`을 이용한 문제라고 생각했습니다
결국 틀렸습니다 사소한 실수를 못 찾고 8시간 동안 봤네요 ㅠㅠ
차성원씨가 찾아줬습니다 진짜 레전드 탐색기
어차피 틀린 접근이었지만 유유
제 풀이는 위에 적은 알고리즘을 활용한 풀이었습니다.
사고 흐름
1. 점수로 정렬한 후 남은 조건을 보자
이게 가장 먼저 생각났습니다.
다른 조건들의 경우 직접 비교하는 수가 최선이지만,
점수의 경우 모두 제시된 점수보다 높은 사람을 원했기에,
정렬과 이진 탐색을 활용하면 되겠다 생각했습니다.
2. 조건을 보는 방법
이게 가장 오래 걸렸고 제 풀이가 틀린 이유인 부분입니다.
한번에 다 붙여서 비교를 해야 하나,
다 분해해서 보는 비교는 어떻게 연결해야 하나,
생각하다가 불현듯 비트 마스킹이 생각나서 이거겠거니 하고 당했습니다.
비트 마스킹을 활용한 방식도 쉽진 않았습니다.
왜냐하면 먼저 언어의 경우 …
=> [PG] 72412. 순위검색 🔢🔍
